import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle455Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedFileHubWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedMyCloudWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedVectorWidget61.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle4523Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedExcelWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle456Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedFrame57Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedPhotoshopWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedBuyStorageWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle4522Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedWordWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle228Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedStoragebarWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedPPtWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedPhotoshopWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedRectangle4521Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/Generated40GBof128GBWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedFileManagerWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedPPWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedPhotoshopWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge2widget/generated/GeneratedSearchWidget2.dart';

/* Frame Android Large - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 127.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: GeneratedFileManagerWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPWidget1(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedFrame57Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedWordWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 81.0,
                child: GeneratedPPtWidget(),
              ),
              Positioned(
                left: 190.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedExcelWidget(),
              ),
              Positioned(
                left: 258.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 33.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 33.0,
                child: GeneratedSearchWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 33.0,
                child: GeneratedRectangle4521Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05114999877081977;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      18.413999557495117;

                  double percentHeight = 0.019267500638961793;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.414000511169434;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.14444444444444443,
                        translateY: constraints.maxHeight * 0.26,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget61())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.030555555555555555;
                  double scaleX = (constraints.maxWidth * percentWidth) / 11.0;

                  double percentHeight = 0.0175;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 14.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2833333333333333,
                        translateY: constraints.maxHeight * 0.26125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget62())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 34.0,
                child: GeneratedRectangle228Widget(),
              ),
              Positioned(
                left: 181.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 28.0,
                child: GeneratedRectangle455Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 25.0,
                child: GeneratedFileHubWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 22.0,
                child: GeneratedMyCloudWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 45.0,
                child: GeneratedRectangle4522Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 3.0,
                child: GeneratedStoragebarWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 33.0,
                child: GeneratedRectangle4523Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 20.0,
                child: GeneratedBuyStorageWidget(),
              ),
              Positioned(
                left: 246.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 14.0,
                child: Generated40GBof128GBWidget(),
              )
            ]),
      ),
    ));
  }
}
