import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedComputersWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedBurakWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedFrame56Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedRakunWorkGroupWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedRectangle4557Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedPPWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge10widget/generated/GeneratedGroup8Widget.dart';

/* Frame Android Large - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 360.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 360.0,
                    height: 800.0,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.0, -1.0),
                        end: Alignment(0.0, 0.9999999999999998),
                        stops: [0.0, 1.0],
                        colors: [
                          Color.fromARGB(255, 174, 161, 229),
                          Color.fromARGB(255, 132, 183, 220)
                        ],
                      ),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 30.0,
                            top: 705.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 65.0,
                            child: GeneratedMenuWidget(),
                          ),
                          Positioned(
                            left: 32.0,
                            top: 386.0,
                            right: null,
                            bottom: null,
                            width: 45.0,
                            height: 21.0,
                            child: GeneratedBurakWidget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 132.0,
                            height: 18.0,
                            child: GeneratedRakunWorkGroupWidget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup12Widget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup8Widget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup13Widget(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup11Widget(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup7Widget(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup14Widget(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup10Widget(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup15Widget(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup9Widget(),
                          ),
                          Positioned(
                            left: 134.0,
                            top: 33.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 29.0,
                            child: GeneratedComputersWidget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPPWidget(),
                          ),
                          Positioned(
                            left: 300.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedFrame56Widget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 1.0,
                            child: GeneratedRectangle4557Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
