import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame43Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedNotWidget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedRectangle456Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame44Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedRectangle4557Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame48Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame42Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame41Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedInhibWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedInhibtorWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedStatusWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame46Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame52Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame47Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedNottWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFrame45Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedPPPWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedRectangle4527Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge13widget/generated/GeneratedFileManagerAllWidget1.dart';

/* Frame Android Large - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 153.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 29.0,
                child: GeneratedStatusWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPPWidget1(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedNottWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget3(),
              ),
              Positioned(
                left: 40.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 582.0,
                height: 554.0,
                child: GeneratedFileManagerAllWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 544.0,
                child: GeneratedInhibWidget1(),
              ),
              Positioned(
                left: 330.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 554.0,
                child: GeneratedInhibtorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 554.0,
                child: GeneratedRectangle4527Widget3(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 645.0,
                child: GeneratedRectangle4557Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedNotWidget4(),
              ),
              Positioned(
                left: 128.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedNotificationsWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedFrame52Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame41Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame45Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame43Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame46Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame42Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame47Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame44Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame48Widget1(),
              )
            ]),
      ),
    ));
  }
}
