import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame44Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup10Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame43Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedRakunWorkGroupWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup14Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup13Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedNotificationsWidget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup12Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame52Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame46Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup9Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame47Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedRectangle4557Widget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedNotWidget7.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup11Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedBurakWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedComputersWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame48Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame42Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame45Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedPPWidget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedFrame41Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedRectangle4558Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedMenuWidget8.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup15Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget1/generated/GeneratedGroup8Widget2.dart';

/* Frame Android Large - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge11Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 360.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 360.0,
                    height: 800.0,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.0, -1.0),
                        end: Alignment(0.0, 0.9999999999999998),
                        stops: [0.0, 1.0],
                        colors: [
                          Color.fromARGB(255, 174, 161, 229),
                          Color.fromARGB(255, 132, 183, 220)
                        ],
                      ),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 30.0,
                            top: 705.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 65.0,
                            child: GeneratedMenuWidget8(),
                          ),
                          Positioned(
                            left: 32.0,
                            top: 386.0,
                            right: null,
                            bottom: null,
                            width: 45.0,
                            height: 21.0,
                            child: GeneratedBurakWidget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 132.0,
                            height: 18.0,
                            child: GeneratedRakunWorkGroupWidget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup12Widget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup8Widget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup13Widget2(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup11Widget2(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup7Widget2(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup14Widget2(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup10Widget2(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup15Widget2(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup9Widget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 645.0,
                            child: GeneratedRectangle4557Widget5(),
                          ),
                          Positioned(
                            left: 134.0,
                            top: 33.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 29.0,
                            child: GeneratedComputersWidget2(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPPWidget4(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 30.0,
                            child: GeneratedRectangle4558Widget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 30.0,
                            child: GeneratedNotWidget7(),
                          ),
                          Positioned(
                            left: 128.0,
                            top: 33.0,
                            right: null,
                            bottom: null,
                            width: 109.0,
                            height: 29.0,
                            child: GeneratedNotificationsWidget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 39.0,
                            right: null,
                            bottom: null,
                            width: 12.0,
                            height: 12.0,
                            child: GeneratedFrame52Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 70.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame41Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 302.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame45Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 186.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame43Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 418.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame46Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 128.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame42Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 360.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame47Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 244.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame44Widget4(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 476.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame48Widget4(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
