import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedPhotoshopWidget6.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedBuyStorageWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedPhotoshopWidget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame46Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame47Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle4521Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedMenuWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedPPWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame41Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle228Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame48Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame45Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/Generated40GBof128GBWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame44Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame42Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle4557Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedExcelWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle4523Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedStoragebarWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle4522Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFileHubWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedSearchWidget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame43Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle455Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFrame52Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedWordWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedNotWidget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedPhotoshopWidget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedFileManagerWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedNotWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedPPtWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedMyCloudWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge12widget/generated/GeneratedRectangle456Widget1.dart';

/* Frame Android Large - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 127.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 26.0,
                child: GeneratedFileManagerWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPWidget2(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedNotWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget4(),
              ),
              Positioned(
                left: 116.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget5(),
              ),
              Positioned(
                left: 48.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedWordWidget2(),
              ),
              Positioned(
                left: 116.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 81.0,
                child: GeneratedPPtWidget1(),
              ),
              Positioned(
                left: 190.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 81.0,
                child: GeneratedExcelWidget2(),
              ),
              Positioned(
                left: 258.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 81.0,
                child: GeneratedPhotoshopWidget6(),
              ),
              Positioned(
                left: 40.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 33.0,
                child: GeneratedSearchWidget3(),
              ),
              Positioned(
                left: 92.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 33.0,
                child: GeneratedSearchWidget5(),
              ),
              Positioned(
                left: 40.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 33.0,
                child: GeneratedRectangle4521Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05114999877081977;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      18.413999557495117;

                  double percentHeight = 0.019267500638961793;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      15.414000511169434;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.14444444444444443,
                        translateY: constraints.maxHeight * 0.26,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget81())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.030555555555555555;
                  double scaleX = (constraints.maxWidth * percentWidth) / 11.0;

                  double percentHeight = 0.0175;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 14.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2833333333333333,
                        translateY: constraints.maxHeight * 0.26125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget82())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 34.0,
                child: GeneratedRectangle228Widget1(),
              ),
              Positioned(
                left: 181.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 28.0,
                child: GeneratedRectangle455Widget1(),
              ),
              Positioned(
                left: 226.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 25.0,
                child: GeneratedFileHubWidget1(),
              ),
              Positioned(
                left: 80.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 22.0,
                child: GeneratedMyCloudWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 45.0,
                child: GeneratedRectangle4522Widget1(),
              ),
              Positioned(
                left: 153.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 3.0,
                child: GeneratedStoragebarWidget1(),
              ),
              Positioned(
                left: 46.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 33.0,
                child: GeneratedRectangle4523Widget1(),
              ),
              Positioned(
                left: 60.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 20.0,
                child: GeneratedBuyStorageWidget1(),
              ),
              Positioned(
                left: 246.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 14.0,
                child: Generated40GBof128GBWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 645.0,
                child: GeneratedRectangle4557Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedNotWidget3(),
              ),
              Positioned(
                left: 128.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedFrame52Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame41Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame45Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame43Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame46Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame42Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame47Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame44Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame48Widget(),
              )
            ]),
      ),
    ));
  }
}
