import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedRectangle4558Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedBurakWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedRectangle4557Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedRakunWorkGroupWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame41Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedComputersWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedMenuWidget7.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame46Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedNotificationsWidget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame45Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup12Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame52Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame47Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame48Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedPPWidget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame43Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame44Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedFrame42Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedNotWidget6.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge11widget/generated/GeneratedGroup10Widget1.dart';

/* Frame Android Large - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 360.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 360.0,
                    height: 800.0,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.0, -1.0),
                        end: Alignment(0.0, 0.9999999999999998),
                        stops: [0.0, 1.0],
                        colors: [
                          Color.fromARGB(255, 174, 161, 229),
                          Color.fromARGB(255, 132, 183, 220)
                        ],
                      ),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 30.0,
                            top: 705.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 65.0,
                            child: GeneratedMenuWidget7(),
                          ),
                          Positioned(
                            left: 32.0,
                            top: 386.0,
                            right: null,
                            bottom: null,
                            width: 45.0,
                            height: 21.0,
                            child: GeneratedBurakWidget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 80.0,
                            right: null,
                            bottom: null,
                            width: 132.0,
                            height: 18.0,
                            child: GeneratedRakunWorkGroupWidget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup12Widget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup8Widget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 95.0,
                            height: 61.0,
                            child: GeneratedGroup13Widget1(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup11Widget1(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup7Widget1(),
                          ),
                          Positioned(
                            left: 133.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup14Widget1(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 111.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup10Widget1(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 417.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup15Widget1(),
                          ),
                          Positioned(
                            left: 236.0,
                            top: 203.0,
                            right: null,
                            bottom: null,
                            width: 94.0,
                            height: 61.0,
                            child: GeneratedGroup9Widget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 645.0,
                            child: GeneratedRectangle4557Widget4(),
                          ),
                          Positioned(
                            left: 134.0,
                            top: 33.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 29.0,
                            child: GeneratedComputersWidget1(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 30.0,
                            height: 30.0,
                            child: GeneratedPPWidget3(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 30.0,
                            child: GeneratedRectangle4558Widget(),
                          ),
                          Positioned(
                            left: 30.0,
                            top: 30.0,
                            right: null,
                            bottom: null,
                            width: 300.0,
                            height: 30.0,
                            child: GeneratedNotWidget6(),
                          ),
                          Positioned(
                            left: 128.0,
                            top: 33.0,
                            right: null,
                            bottom: null,
                            width: 109.0,
                            height: 29.0,
                            child: GeneratedNotificationsWidget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 39.0,
                            right: null,
                            bottom: null,
                            width: 12.0,
                            height: 12.0,
                            child: GeneratedFrame52Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 70.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame41Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 302.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame45Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 186.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame43Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 418.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame46Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 128.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame42Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 360.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame47Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 244.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame44Widget3(),
                          ),
                          Positioned(
                            left: 39.0,
                            top: 476.0,
                            right: null,
                            bottom: null,
                            width: 280.0,
                            height: 48.0,
                            child: GeneratedFrame48Widget3(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
