import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedPPpPWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedRectangle4548Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedRectangle4549Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedRectangle4528Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame59Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame33Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedMenuWidget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame30Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame32Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame31Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame26Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedRectangle456Widget4.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame28Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame34Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame36Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge7widget/generated/GeneratedFrame29Widget.dart';

/* Frame Android Large - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 146.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 29.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPpPWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedFrame59Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget4(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 588.0,
                child: GeneratedRectangle4528Widget2(),
              ),
              Positioned(
                left: 41.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 18.154727935791016,
                height: 22.0,
                child: GeneratedFrame30Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 18.187358856201172,
                child: GeneratedFrame29Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 13.181818962097168,
                child: GeneratedFrame28Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 17.11111068725586,
                child: GeneratedFrame27Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedFrame26Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 11.25,
                child: GeneratedFrame31Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 20.0,
                child: GeneratedFrame32Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 16.0,
                child: GeneratedFrame33Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 18.170650482177734,
                height: 18.61345863342285,
                child: GeneratedFrame34Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 12.0,
                child: GeneratedFrame35Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 599.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 28.0,
                child: GeneratedRectangle4548Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedRectangle4549Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 13.0,
                child: GeneratedFrame36Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget5(),
              )
            ]),
      ),
    ));
  }
}
