import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedInhibWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedMenuWidget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedPPPWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedRectangle456Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedInhibtorWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedFrame58Widget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedStatusWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedFileManagerAllWidget.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge3widget/generated/GeneratedRectangle4527Widget1.dart';

/* Frame Android Large - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 153.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 29.0,
                child: GeneratedStatusWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPPWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedFrame58Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 582.0,
                height: 554.0,
                child: GeneratedFileManagerAllWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 544.0,
                child: GeneratedInhibWidget(),
              ),
              Positioned(
                left: 330.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 554.0,
                child: GeneratedInhibtorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 554.0,
                child: GeneratedRectangle4527Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget3(),
              )
            ]),
      ),
    ));
  }
}
