import 'package:flutter/material.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame26Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame42Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedRectangle4557Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame41Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedRectangle4528Widget3.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame27Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame48Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame35Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame29Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame52Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame46Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame33Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedMenuWidget6.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame43Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame28Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame31Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedNotWidget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame44Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame32Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedPPpPWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame45Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedRectangle4548Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedNotificationsWidget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedNotttWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame30Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame47Widget2.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedRectangle456Widget5.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame36Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedFrame34Widget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/fff2app/generatedandroidlarge14widget/generated/GeneratedRectangle4549Widget1.dart';

/* Frame Android Large - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 174, 161, 229),
              Color.fromARGB(255, 132, 183, 220)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 146.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 29.0,
                child: GeneratedSettingsWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPPpPWidget1(),
              ),
              Positioned(
                left: 300.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedNotttWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 588.0,
                child: GeneratedRectangle456Widget5(),
              ),
              Positioned(
                left: 30.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 588.0,
                child: GeneratedRectangle4528Widget3(),
              ),
              Positioned(
                left: 41.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 18.154727935791016,
                height: 22.0,
                child: GeneratedFrame30Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 18.187358856201172,
                child: GeneratedFrame29Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 13.181818962097168,
                child: GeneratedFrame28Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 17.11111068725586,
                child: GeneratedFrame27Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedFrame26Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 11.25,
                child: GeneratedFrame31Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 20.0,
                child: GeneratedFrame32Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 16.0,
                child: GeneratedFrame33Widget1(),
              ),
              Positioned(
                left: 41.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 18.170650482177734,
                height: 18.61345863342285,
                child: GeneratedFrame34Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 12.0,
                child: GeneratedFrame35Widget1(),
              ),
              Positioned(
                left: 85.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 599.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 28.0,
                child: GeneratedRectangle4548Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedRectangle4549Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 13.0,
                child: GeneratedFrame36Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 65.0,
                child: GeneratedMenuWidget6(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 645.0,
                child: GeneratedRectangle4557Widget3(),
              ),
              Positioned(
                left: 30.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedNotWidget5(),
              ),
              Positioned(
                left: 128.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 29.0,
                child: GeneratedNotificationsWidget2(),
              ),
              Positioned(
                left: 39.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedFrame52Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame41Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame45Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame43Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame46Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame42Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame47Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame44Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 48.0,
                child: GeneratedFrame48Widget2(),
              )
            ]),
      ),
    ));
  }
}
